# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_virtual_network_data = {
  virtual_network_1 = {
    enabled             = true
    location            = "eastus"
    name                = "example-vnet-01"
    resource_group_name = "example-rg-01"
    address_space       = ["10.0.0.0/16"]
  }
}
