# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_key_vault_data = {
  key_vault_1 = {
    location            = "eastus"
    name                = "example-keyvault-01"
    resource_group_name = "example-rg-01"
    sku_name            = "standard"
    tenant_id           = "00000000-0000-0000-0000-000000000000"
    tenant_name         = "example-tenant-01"
  }
}