# hashicorp time v0.13.1
# Generated by local AI (qwen3-coder:latest)
time_offset_data = {
  offset_days = {
    enabled     = true
    offset_days = 5
  }
  offset_hours = {
    enabled      = true
    offset_hours = 3
  }
}
