# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_nat_gateway_public_ip_prefix_association_data = {
  nat_gateway_public_ip_prefix_association_1 = {
    nat_gateway_id      = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-rg-01/providers/Microsoft.Network/natGateways/example-natgateway-01"
    public_ip_prefix_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-rg-01/providers/Microsoft.Network/publicIPPrefixes/example-publicipprefix-01"
  }
}