# -----------------------------------------
# Terraform Module
# Contributor(s): William Robinson
# Updated: March 2026
# Purpose: Terraform Resource Module
# -----------------------------------------
# hashicorp azurerm v4.60.0 2026022402
# Generated by azure-ai-foundry AI (gpt-5-chat)
azurerm_databricks_workspace_data = {
  databricks_workspace_1 = {
    enabled             = true
    location            = "eastus"
    name                = "example-databricks-workspace-01"
    resource_group_name = "example-resource-group-01"
    sku                 = "premium"
  }
  databricks_workspace_2 = {
    enabled                               = false
    sku                                   = "premium"
    location                              = "westus2"
    resource_group_name                   = "databricks-rg"
    name                                  = "workspace_name"
    public_network_access_enabled         = false
    network_security_group_rules_required = "AllRules"
    managed_resource_group_name           = "managed-databricks-rg"

    custom_parameters = {
      storage_account_name                                  = "backend_storage_account_name"
      storage_account_sku_name                              = "Standard_RAGRS"
      no_public_ip                                          = true
      virtual_network_name                                  = "vnet_name"
      public_subnet_name                                    = "public_subnet_name"
      private_subnet_name                                   = "private_subnet_name"
      public_subnet_network_security_group_association_key  = "public_subnet_network_security_group_association_key"
      private_subnet_network_security_group_association_key = "private_subnet_network_security_group_association_key"
    }
  }
}
