# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_subnet_nat_gateway_association_data = {
  subnet_nat_gateway_association_1 = {
    nat_gateway_id   = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-rg-01/providers/Microsoft.Network/natGateways/example-natgateway-01"
    nat_gateway_name = "example-natgateway-01"
    subnet_id        = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-rg-01/providers/Microsoft.Network/virtualNetworks/example-vnet-01/subnets/example-subnet-01"
    subnet_name      = "example-subnet-01"
  }
}