# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_network_security_group_data = {
  network_security_group_1 = {
    location            = "eastus"
    name                = "example-nsg-01"
    resource_group_name = "example-rg-01"
  }
}