# databricks databricks v1.114.2
# Generated by local AI (qwen3-coder:latest)
databricks_group_member_data = {
  account_group_member = {
    enabled        = true
    group_id       = "00000000-0000-0000-0000-000000000000"
    member_id      = "11111111-1111-1111-1111-111111111111"
    provider_scope = "account"
  }
  workspace_group_member = {
    enabled        = true
    group_id       = "00000000-0000-0000-0000-000000000000"
    member_id      = "11111111-1111-1111-1111-111111111111"
    provider_scope = "workspace"
  }
}
