# hashicorp time v0.13.1
# Generated by local AI (qwen3-coder:latest)
time_static_data = {
  static_time = {
    enabled = true
  }
  static_time_triggers = {
    enabled = false

    triggers = {
      value = "example-trigger"
    }
  }
}
