# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_resource_group_data = {
  resource_group_1 = {
    enabled  = true
    location = "eastus"
    name     = "example-rg-01"
  }
}