# hashicorp time v0.13.1
# Generated by local AI (qwen3-coder:latest)
time_sleep_data = {
  create_duration = {
    enabled         = true
    create_duration = "1s"
  }
  destroy_duration = {
    enabled          = true
    destroy_duration = "1s"
  }
}
