# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_route_table_data = {
  route_table_1 = {
    enabled             = true
    location            = "eastus"
    name                = "example-route-table-01"
    resource_group_name = "example-rg-01"
  }
}
