# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_public_ip_prefix_data = {
  public_ip_prefix_1 = {
    enabled             = true
    location            = "eastus"
    name                = "example-public-ip-prefix-01"
    resource_group_name = "example-rg-01"
  }
}