# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_subnet_route_table_association_data = {
  subnet_route_table_association_1 = {
    enabled.         = true
    route_table_id   = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-rg-01/providers/Microsoft.Network/routeTables/example-route-table-01"
    subnet_id        = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-rg-01/providers/Microsoft.Network/virtualNetworks/example-vnet-01/subnets/example-subnet-01"
    route_table_name = "example-route-table-01"
    subnet_name      = "example-subnet-01"
  }
}
