# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_subnet_network_security_group_association_data = {
  subnet_network_security_group_association_1 = {
    network_security_group_id   = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-rg-01/providers/Microsoft.Network/networkSecurityGroups/example-nsg-01"
    network_security_group_name = "example-nsg-01"
    subnet_id                   = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-rg-01/providers/Microsoft.Network/virtualNetworks/example-vnet-01/subnets/example-subnet-01"
    subnet_name                 = "example-subnet-01"
  }
}