# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_nat_gateway_data = {
  nat_gateway_1 = {
    enabled             = true
    location            = "eastus"
    name                = "example-natgateway-01"
    resource_group_name = "example-rg-01"
  }
}
