# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_user_assigned_identity_data = {
  user_assigned_identity_1 = {
    enabled             = true
    location            = "eastus"
    name                = "example-identity-01"
    resource_group_name = "example-rg-01"
  }
}
