# databricks databricks v1.114.2
# Generated by local AI (qwen3-coder:latest)
databricks_group_data = {
  account = {
    enabled              = true
    display_name         = "example-group-01"
    allow_cluster_create = true
  }
  workspace = {
    enabled          = true
    display_name     = "example-workspace_group-01"
    workspace_access = true
    provider_scope   = "workspace"
  }
}
