# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_subnet_data = {
  subnet_1 = {
    enabled              = true
    name                 = "example-subnet-01"
    resource_group_name  = "example-rg-01"
    virtual_network_name = "example-vnet-01"
    address_prefix       = ["10.0.1.0/24"]
  }
}
