# hashicorp time v0.13.1
# Generated by local AI (qwen3-coder:latest)
time_rotating_data = {
  rotation_days = {
    enabled       = true
    rotation_days = 365
  }
  rotation_months = {
    enabled         = true
    rotation_months = 12
  }
}
