# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_public_ip_data = {
  public_ip_1 = {
    enabled.            = true
    allocation_method   = "Static"
    location            = "eastus"
    name                = "example-pip-01"
    resource_group_name = "rg-example-01"
  }
}
