# hashicorp azurerm v4.71.0
# Generated by local AI (qwen3-coder:latest)
azurerm_custom_ip_prefix_data = {
  custom_ip_prefix_1 = {
    cidr                = "10.0.0.0/24"
    location            = "eastus"
    name                = "example-custom-ip-prefix-01"
    resource_group_name = "example-rg-01"
  }
}